@OrderService_HostAddress = http://localhost:5298

# GET {{OrderService_HostAddress}}/weatherforecast/
# Accept: application/json

GET {{OrderService_HostAddress}}/Order/
Accept: application/json
###
